-- Preview first 10 rows
SELECT *
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS"
LIMIT 10;

-- Unique product categories
SELECT DISTINCT PRODUCT_CATEGORY
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS";

-- Revenue per transaction
SELECT 
  TRANSACTION_ID,
  TRANSACTION_QTY * UNIT_PRICE AS REVENUE
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS";

-- Number of unique shops
SELECT COUNT(DISTINCT STORE_ID) AS NUMBER_OF_SHOPS
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS";

-- Total number of transactions
SELECT COUNT(TRANSACTION_ID) AS NUMBER_OF_TRANSACTIONS
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS";

-- Unique store locations and IDs
SELECT DISTINCT STORE_LOCATION, STORE_ID
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS";

-- Earliest transaction date (shop opening)
SELECT MIN(TRANSACTION_DATE) AS SHOP_OPENING_DATE
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS";

-- Latest transaction date (last operating day)
SELECT MAX(TRANSACTION_DATE) AS LAST_OPERATING_DATE
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS";

-- Unique store locations
SELECT DISTINCT STORE_LOCATION
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS";

-- Revenue by store location
SELECT 
  STORE_LOCATION,
  SUM(TRANSACTION_QTY * UNIT_PRICE) AS REVENUE
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS"
GROUP BY STORE_LOCATION;

-- Day name and month name
SELECT 
  DAYNAME(TRANSACTION_DATE) AS DAY_NAME,
  MONTHNAME(TRANSACTION_DATE) AS MONTH_NAME
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS";

-- Classify transactions by weekday/weekend
SELECT 
  TRANSACTION_DATE,
  DAYNAME(TRANSACTION_DATE) AS DAY_NAME,
  CASE
    WHEN DAYNAME(TRANSACTION_DATE) IN ('SAT', 'SUN') THEN 'WEEKEND'
    ELSE 'WEEKDAY'
  END AS DAY_CLASSIFICATION
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS";

-- Store opening and closing hours
SELECT 
  STORE_LOCATION,
  MIN(TRANSACTION_TIME) AS OPENING_HOUR,
  MAX(TRANSACTION_TIME) AS CLOSING_HOUR
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS"
GROUP BY STORE_LOCATION;

-- Time-of-day classification and revenue
SELECT 
  PRODUCT_CATEGORY,
  STORE_LOCATION,
  TRANSACTION_DATE,
  TRANSACTION_TIME,
  CASE 
    WHEN TRANSACTION_TIME BETWEEN '06:00:00' AND '11:59:59' THEN 'MORNING'
    WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '15:59:59' THEN 'AFTERNOON'
    WHEN TRANSACTION_TIME BETWEEN '16:00:00' AND '19:59:59' THEN 'EVENING'
    ELSE 'NIGHT'
  END AS TIME_BUCKET,
  SUM(TRANSACTION_QTY * UNIT_PRICE) AS REVENUE
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS"
WHERE TRANSACTION_DATE > '2023-05-01'
GROUP BY 
  PRODUCT_CATEGORY,
  STORE_LOCATION,
  TRANSACTION_DATE,
  TRANSACTION_TIME,
  CASE 
    WHEN TRANSACTION_TIME BETWEEN '06:00:00' AND '11:59:59' THEN 'MORNING'
    WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '15:59:59' THEN 'AFTERNOON'
    WHEN TRANSACTION_TIME BETWEEN '16:00:00' AND '19:59:59' THEN 'EVENING'
    ELSE 'NIGHT'
  END
ORDER BY REVENUE DESC;

-- Revenue by product category and time
SELECT 
  PRODUCT_CATEGORY,
  TRANSACTION_DATE,
  TRANSACTION_TIME,
  SUM(TRANSACTION_QTY * UNIT_PRICE) AS REVENUE
FROM "CASESTUDY"."BRIGHTCOFEESHOP"."BRIGHTCOFFEESHOPDATAANALYSIS"
GROUP BY 
  PRODUCT_CATEGORY,
  STORE_LOCATION,
  TRANSACTION_DATE,
  TRANSACTION_TIME;
